### ISSUE TITLE
Crash on x86 in dm::Memory::init() due 1.5Gb allocaton

### ISSUE THREAD

**Issue by Raikiri** [dariomanesku/dm#1]
Build of cmftStudio from sources under windows crashes on program startup in allocator.h because it tries to preallocate 1.5Gb of memory in a single huge chunk of size
`    #define DM_MEM_DEFAULT_SIZE        DM_MEGABYTES(1536)`
which apparently fails. Either building the program as x64 or setting 
`#define DM_ALLOCATOR 0`
work around the problem, however, I think a more careful approach to memory preallocation should be considered.

**Comment by dariomanesku** [comment]
Yeah, it's possible that something is wrong there, I wasn't paying much attention to 32bit builds. I will perhaps have a look at that, but you should use 64bit build anyway. In case you don't want that 1.5GB allocation at startup, settings DM_ALLOCATOR 0 will fall back to c-runtime allocator. Dm Allocator is much faster though (I don't have any numbers right now, but that's certainly the case).
